name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '00 21 */8 * *'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
        ./IBM_Cloud_CLI/ibmcloud config --check-version=false
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
        IBM_PWD: ${{ secrets.IBM_PWD }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login -a "https://cloud.ibm.com" -r "us-south" -u "$IBM_ACCOUNT" -p "$IBM_PWD"
    - name: Target IBM Cloud
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf install -f -v 6.15.0
        ./IBM_Cloud_CLI/ibmcloud target --cf
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME_ONE: ${{ secrets.IBM_APP_NAME_ONE }}
        IBM_APP_NAME_TWO: ${{ secrets.IBM_APP_NAME_TWO }}
        IBM_APP_NAME_THREE: ${{ secrets.IBM_APP_NAME_THREE }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME_ONE"
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME_TWO"
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME_THREE"
